spring:
  profile:
    active: local
  application:
    name: labs

application:
  rating-service:
    base-path: http://localhost:8089
    ratings: ${application.rating-service.base-path}/rating-service/v1/ratings
  feature:
    toggles:
      cosmo-cats: true
      kitty-products: false

spring:
  config:
    activate:
      on-profile: dev
application:
  feature:
    cosmoCats: true
    kittyProducts: false


