logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client: DEBUG
spring:
  profiles:
    active: local
  application:
    name: labs
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS256 # default actually
          jwk-set-uri: http://localhost:8083/.well-known/jwks.json
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            scope: user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            authorization-grant-type: authorization_code
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        jdbc.batch_size: 15
        order_inserts: true
        order_updates: true
        query.fail_on_pagination_over_collection_fetch: true
        query.in_clause_parameter_padding: true
        connection.provider_disables_autocommit: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/galactic_cats
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
      pool-name: galactic-market
  liquibase:
    change-log: classpath:liquibase/changelog.yaml
    enabled: true

application:
  rating-service:
    base-path: http://localhost:8089
    ratings: ${application.rating-service.base-path}/rating-service/v1/ratings
  feature:
    toggles:
      cosmo-cats: true
      kitty-products: false

---
spring:
  config:
    activate:
      on-profile: dev
application:
  feature:
    toggles:
      cosmo-cats: true
      kitty-products: false
